### ISSUE TITLE
upgrade to pug 2.0 

### ISSUE THREAD

**Issue by vastbinderj** [ottemo/ottemo.io#1]
there was a trademark conflict with jade in the node project. we need to upgrade to pug 2.0 and make sure everything looks good. 

rule number 1 - we will deploy the new site to firebase - do not store the firebase credentials in this repository, it is public and will remain so. 
rule number 2 - do not reference crendentials in issues or comments on github

## Tasks

- [ ] upgrade to the latest version of node and see if the site can be run in development mode
- [ ] review release notes for jade/pug and fix any potential issues 
- [ ] get the site running on your local using pug 2.0 and the latest version of node - post a screenshot here once you have verified the entire site looks exactly like the site running in production today
- [ ] update the README for how to run the site in development mode
- [ ] create a pull request for either @vnaz or @vastbinderj to review
